(component
  (core module $Main
    (memory (export "memory") 1)
    (global $count (mut i32) (i32.const 0))
    (func (export "turn") (result i32)
      (global.set $count (i32.add (global.get $count) (i32.const 1)))
      (i32.add (global.get $count) (i32.const OFFSET)))
    (func (export "save") (result i32)
      (i32.store (i32.const 128) (global.get $count))
      (i32.store (i32.const 64) (i32.const 128))
      (i32.store (i32.const 68) (i32.const 4))
      (i32.const 64))
    (func (export "restore") (param $at i32) (param $len i32)
      (if (i32.eq (local.get $len) (i32.const 4))
        (then (global.set $count (i32.load (local.get $at))))))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (i32.const 256))
  )
  (core instance $main (instantiate $Main))
  (func (export "turn") (result u32)
    (canon lift (core func $main "turn")))
  (func (export "save") (result (list u8))
    (canon lift (core func $main "save") (memory $main "memory")))
  (func (export "restore") (param "state" (list u8))
    (canon lift (core func $main "restore") (memory $main "memory") (realloc (func $main "realloc"))))
)
